name: brain_tumor_detection
description: 'Brain Tumor Detection using YOLO'
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.6.0 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    image_picker: ^1.1.2
    provider: ^6.1.5
    dio: ^5.8.0+1
    flutter_dotenv: ^5.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - .env
